[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mdlthermo"
version = "0.1.0"
description = "Thermophysical property prediction modules"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
  "numpy==2.4.1",
  "pillow==12.1.0",
  "rdkit==2025.9.3",
  "scipy==1.17.0",
  "setuptools==80.10.1",
]

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
COSMOSAC = [
  "InChIKey_to_index.json",
  "cosmo_files/*.cosmo",
  "model_parameters/**",
]
GCGCN = ["parameters/**"]
UNIFAC = ["NIST/**"]
VaporPressure = ["Equations/**", "GCGCN/**"]
Prediction = ["GCGCN/Parameters/**"]
