[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mdlthermo"
version = "0.1.0"
description = "Thermodynamics modeling package"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Author Name", email = "author@example.com" }
]
dependencies = [
    "numpy>=2.4.1",
    "pillow>=12.1.0",
    "rdkit>=2025.9.3",
    "scipy>=1.17.0",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["modules*"]
